version: '3.9'
services:
  boiler-plate:
    container_name: boiler-plate
    build:
      context: .
      dockerfile: ./build/Dockerfile
    volumes:
      - ./work:/go/work
    tty: true
    env_file:
      - ./build/.go_env
    environment:
      - TZ=Asia/Tokyo
    ports:
      - "3000:8080"
    network_mode: host
